// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyyyHBQQx7fOKkTrRAFTnxB_anRfE7cDw',
    appId: '1:246349789496:web:4b77d314252efab950a9cd',
    messagingSenderId: '246349789496',
    projectId: 'flutter-project-9534d',
    authDomain: 'flutter-project-9534d.firebaseapp.com',
    storageBucket: 'flutter-project-9534d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: "AIzaSyD5FEt2WZADFKCWqnUNgO8BtoGKG502qq0",
      authDomain: "kinjalflutter.firebaseapp.com",
      projectId: "kinjalflutter",
      storageBucket: "kinjalflutter.appspot.com",
      messagingSenderId: "876432354980",
      appId: "1:876432354980:web:66d002a75e7cd7f59c0031",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4qaA461Ygn1-V0b4xm4vFmoS1CsPpdI8',
    appId: '1:246349789496:ios:2499b51234f7975c50a9cd',
    messagingSenderId: '246349789496',
    projectId: 'flutter-project-9534d',
    storageBucket: 'flutter-project-9534d.appspot.com',
    iosClientId: '246349789496-p87t36ekf1t7t1l4goc3o1d7uphdbggn.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyyyHBQQx7fOKkTrRAFTnxB_anRfE7cDw',
    appId: '1:246349789496:web:cfc66e9e91fa937750a9cd',
    messagingSenderId: '246349789496',
    projectId: 'flutter-project-9534d',
    authDomain: 'flutter-project-9534d.firebaseapp.com',
    storageBucket: 'flutter-project-9534d.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4qaA461Ygn1-V0b4xm4vFmoS1CsPpdI8',
    appId: '1:246349789496:ios:2499b51234f7975c50a9cd',
    messagingSenderId: '246349789496',
    projectId: 'flutter-project-9534d',
    storageBucket: 'flutter-project-9534d.appspot.com',
    iosClientId: '246349789496-p87t36ekf1t7t1l4goc3o1d7uphdbggn.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningApp',
  );

}